LEVELS = (
    dict(starting=[1, 1, 1, 1],
         puck_speed=2.5,
         empty_speed=4.5,
         respawn_rate=184),
    dict(starting=[1, 2, 2, 1],
         puck_speed=3.0,
         empty_speed=4.5,
         respawn_rate=184),
    dict(starting=[4, 2, 2, 4],
         puck_speed=3.5,
         empty_speed=4.5,
         respawn_rate=215),
    dict(starting=[4, 4, 4, 4],
         puck_speed=2.5,
         empty_speed=5.5,
         respawn_rate=133),
)
